{"version":3,"sources":["src/definition/exceptions/AppsEngineException.ts"],"names":[],"mappings":";;;AAAA;;;;;;;;;;;;GAYG;AACH,MAAa,mBAAoB,SAAQ,KAAK;IAK1C,YAAY,OAAgB;QACxB,KAAK,EAAE,CAAC;QALL,SAAI,GAAG,qBAAqB,CAAC;QAMhC,IAAI,CAAC,OAAO,GAAG,OAAO,CAAC;IAC3B,CAAC;IAEM,YAAY;QACf,OAAO;YACH,IAAI,EAAE,IAAI,CAAC,IAAI;YACf,OAAO,EAAE,IAAI,CAAC,OAAO;SACxB,CAAC;IACN,CAAC;CACJ;AAhBD,kDAgBC","file":"AppsEngineException.js","sourcesContent":["/**\n * The internal exception from the framework\n *\n * It's used to signal to the outside world that\n * a _known_ exception has happened during the execution\n * of the apps.\n *\n * It's the base exception for other known classes\n * such as UserNotAllowedException, which is used\n * to inform the host that an app identified\n * that a user cannot perform some action, e.g.\n * join a room\n */\nexport class AppsEngineException extends Error {\n    public name = 'AppsEngineException';\n\n    public message: string;\n\n    constructor(message?: string) {\n        super();\n        this.message = message;\n    }\n\n    public getErrorInfo() {\n        return {\n            name: this.name,\n            message: this.message,\n        };\n    }\n}\n"]}